server:
  port: 3000
  servlet:
    context-path: /currency-exchange/api/v1

spring:
  h2:
    console:
      enabled: true       # Enable H2 web console
      path: /h2-console
  datasource:
      url: jdbc:h2:file:./h2-data
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
      open-in-view: false
      show-sql: true
      properties:
        hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update

  main.banner-mode: "off"